#!/usr/bin/env python3
"""Third-party license inventory generator and the blocking license gate.

PDF-02. This script is the engine behind `make licenses` and the `license-gate`
CI job. It defends claim G2 (PLAN.md §2): *Apache-2.0 with a machine-checked
guarantee that no AGPL/GPL/LGPL code is reachable*.

Two subcommands:

  generate  writes THIRD_PARTY_LICENSES, and website/src/data/licenses.json
            when website/src/data/ exists (PDF-16 consumes it).
  check     the blocking gate: fails on any denied or UNKNOWN license in the
            distributed closure, and asserts the pinned resolution did not
            miss a marker-conditional package.

WHICH ENVIRONMENT IS MEASURED, AND WHY IT IS NOT THE AMBIENT ONE
----------------------------------------------------------------
The blocking gate measures the *distributed* closure:

    UV_PROJECT_ENVIRONMENT=.venv-licenses uv sync --locked --no-dev --all-extras --python 3.11

never the ambient venv. The developer's venv is Python 3.14 with dev
dependencies installed; the CI leg is 3.11 without them. Generating from
whichever venv happens to be active makes THIRD_PARTY_LICENSES differ between
a laptop and CI, and the freshness diff then fails on a machine difference
rather than on real drift (PDF-02 Design §4.2).

Determinism is a first-class requirement: fixed header, `sorted()` on the exact
package name (codepoint order, locale-independent by construction), LC_ALL=C
for every subprocess, `\n` line endings, single trailing newline. A sibling
cycle shipped a locale-collation-sensitive digest that every local gate passed
and the pushed gate caught; this pre-empts that class.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
VENV = ROOT / ".venv-licenses"
VENV_DEV = ROOT / ".venv-licenses-dev"
PINNED_PYTHON = "3.11"
INVENTORY = ROOT / "THIRD_PARTY_LICENSES"
WEBSITE_DATA_DIR = ROOT / "website" / "src" / "data"
WEBSITE_JSON = WEBSITE_DATA_DIR / "licenses.json"
# The distribution name of this project itself. Excluded from the GENERATED
# artifacts (see cmd_generate) but NOT from the blocking check.
SELF = "pdf-tooling"

# PLAN.md §7.2 mechanism 1 + §12 R-11. THIS PATTERN IS THE PRODUCT'S ENTIRE PITCH.
# Widening it is a defect, not caution: MPL-2.0 is PERMITTED and RECORDED
# (pikepdf bundles libqpdf; LibreOffice is MPL-2.0). A gate that reddens on
# pikepdf is broken.
DENY = re.compile(r"AGPL|GPL|LGPL", re.IGNORECASE)
# Spelling alias for the SAME three licenses written out in full, as some
# packages' metadata does ("GNU Lesser General Public License v3"). An alias,
# NOT a widening: it matches AGPL/LGPL/GPL prose and nothing else. Note it does
# NOT match "Mozilla Public License" — MPL is permitted (R-11).
DENY_PROSE = re.compile(r"General Public License", re.IGNORECASE)

# Explicit, commented allowlist. CURRENTLY EMPTY AND EXPECTED TO STAY EMPTY.
# An entry here is a deliberate, reviewed exception; each value states the
# verified license and why the obligation does not reach this product.
#
# It is empty even though the closure contains one package with GPL text in its
# metadata (pyphen) — see `evaluate_expression` below. A disjunctively licensed
# package is not an exception to the policy, it is a package the policy permits
# under one of its own alternative terms, so allowlisting it would be the wrong
# mechanism and would hide it behind a static dict instead of re-deciding it on
# every single run against live metadata.
ALLOWLIST: dict[str, str] = {}

# Packages that exist in the UNIVERSAL lock closure but cannot install under the
# pinned measurement resolution (linux / CPython / 3.11), so the pinned
# pip-licenses run structurally cannot see them. Each entry records the license
# verified from the distribution's own metadata. AC14: an unlisted universal-only
# package fails the gate by name rather than passing unmeasured.
MARKER_ONLY: dict[str, str] = {
    # fonttools[woff] selects brotlicffi instead of brotli off CPython
    # (marker: platform_python_implementation != "CPython"). MIT.
    "brotlicffi": "MIT",
    # typer/click console colour shim, Windows-only (marker: sys_platform == 'win32'
    # / platform_system == 'Windows'). BSD-3-Clause.
    "colorama": "BSD-3-Clause",
}

UNKNOWN = "UNKNOWN"

HEADER = """\
Third-party licenses for pdf-toolkit.
Generated by `make licenses` from uv.lock (runtime closure, --no-dev --all-extras,
Python 3.11, linux). Do not hand-edit — CI regenerates and diffs this file.
pdf-toolkit itself is excluded: it is the first party, not a third party, and it
declares this file in [project] license-files, so including it would make the
inventory contain a copy of itself and depend on how it was last built.
"""


def _clean_env(**overrides: str) -> dict[str, str]:
    """A deterministic, locale-pinned, uv-hermetic environment.

    UV_FROZEN / UV_LOCKED are STRIPPED, not inherited. They are mutually
    exclusive with the flags this script passes explicitly (`uv sync --locked`
    fails under UV_FROZEN; `uv tree --frozen` fails under UV_LOCKED), so a
    caller's ambient setting -- CI sets UV_LOCKED=1 workflow-wide so that
    Makefile-internal `uv run` cannot re-resolve the lockfile -- would
    otherwise break the generator in CI only. This script states its own
    lockfile discipline on every command line; it does not inherit one.

    UV_PROJECT_ENVIRONMENT is stripped for the same reason: this script chooses
    which environment it measures, and inheriting that choice is precisely the
    ambient-venv bug Design §4.2 exists to prevent.
    """
    env = dict(os.environ)
    for leaked in ("UV_FROZEN", "UV_LOCKED", "UV_PROJECT_ENVIRONMENT", "VIRTUAL_ENV"):
        env.pop(leaked, None)
    env["LC_ALL"] = "C"
    env["LANG"] = "C"
    env.update(overrides)
    return env


def _run(cmd: list[str], **kw: Any) -> subprocess.CompletedProcess[str]:
    """Run a command with a deterministic, locale-pinned environment."""
    return subprocess.run(  # noqa: S603
        cmd, check=True, text=True, cwd=ROOT, env=_clean_env(), **kw
    )


def ensure_pinned_env(include_dev: bool = False) -> Path:
    """Materialize the dedicated measurement environment and return its python.

    include_dev=False is the BLOCKING measurement: the distributed closure.
    include_dev=True is the informational dev-tree run of PLAN §7.3 — reported,
    never blocking, because a GPL dev tool is not on the product's call graph.
    """
    target = VENV_DEV if include_dev else VENV
    env = _clean_env(UV_PROJECT_ENVIRONMENT=str(target))
    scope = "--all-extras" if include_dev else "--no-dev --all-extras"
    print(
        f"[licenses] syncing measurement env {target.name} ({scope} --python {PINNED_PYTHON})",
        file=sys.stderr,
    )
    subprocess.run(  # noqa: S603
        [
            "uv",
            "sync",
            "--locked",
            *([] if include_dev else ["--no-dev"]),
            "--all-extras",
            "--python",
            PINNED_PYTHON,
        ],
        check=True,
        text=True,
        cwd=ROOT,
        env=env,
    )
    python = target / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    if not python.exists():
        raise SystemExit(f"measurement env has no interpreter at {python}")
    return python


def pip_licenses(python: Path, *extra: str) -> str:
    """Invoke pip-licenses against the measurement env, not the ambient one.

    pip-licenses reads the *running* interpreter's importlib.metadata, so it is
    run from the dev environment (where it is installed) and pointed at the
    measurement environment with --python. Installing it INTO the measured env
    would make it appear in its own listing and corrupt the artifact.
    """
    cmd = [
        sys.executable,
        "-m",
        "piplicenses",
        "--with-system",
        "--python",
        str(python),
        *extra,
    ]
    return _run(cmd, stdout=subprocess.PIPE).stdout


def rows(python: Path, *, ignore_self: bool = False) -> list[dict[str, str]]:
    extra = ["--ignore-packages", SELF] if ignore_self else []
    data = json.loads(pip_licenses(python, "--format=json", *extra))
    # Codepoint sort on the exact package name: deterministic and
    # locale-independent by construction (Design §4.2).
    return sorted(data, key=lambda r: str(r["Name"]))


def normalize(name: str) -> str:
    """PEP 503 name normalization, so pdfminer.six == pdfminer-six."""
    return re.sub(r"[-_.]+", "-", name).strip().lower()


def split_disjuncts(expression: str) -> list[str]:
    """Split a license expression into its ALTERNATIVE terms.

    pip-licenses emits two disjunctive forms, both of which mean "the recipient
    may choose any one of these":

      * SPDX     -- "Apache-2.0 OR BSD-3-Clause"      (cryptography, packaging)
      * multiple -- "GPLv2+; LGPLv2+; MPL 1.1"        (pyphen)
        classifiers  joined with "; " by pip-licenses

    "X or later" is a VERSION QUALIFIER, not a disjunction, so lowercase " or "
    is never a separator here — see the comment on the separator tuple.

    Conjunction is NOT split: " AND " means every obligation attaches at once,
    so an expression containing a denied term under AND stays denied. Commas are
    not split either — they are used for informal enumerations that are not
    reliably a choice (e.g. pypdfium2's "BSD-3-Clause, Apache-2.0, dependency
    licenses"), and treating an ambiguous separator as a choice is exactly the
    kind of silent widening R-11 forbids.
    """
    parts = [expression]
    # ONLY ";" and SPDX's uppercase " OR ". Lowercase " or " is deliberately NOT
    # a separator: "GNU General Public License v2 or later" would split into
    # ["GNU General Public License v2", "later"], and the bare word "later"
    # matches neither deny pattern — a false PASS on a pure-GPL package. Failing
    # to split a genuine lowercase disjunction is the safe direction (the whole
    # expression stays denied); splitting an "or later" version qualifier is not.
    for separator in (";", " OR "):
        nxt: list[str] = []
        for part in parts:
            nxt.extend(part.split(separator))
        parts = nxt
    return [p.strip() for p in parts if p.strip()]


def is_denied(term: str) -> bool:
    return bool(DENY.search(term) or DENY_PROSE.search(term))


def evaluate_expression(expression: str) -> tuple[bool, str | None, list[str]]:
    """Decide one license expression.

    Returns (permitted, permissive_term_relied_on, denied_terms).

    A package is permitted when AT LEAST ONE of its alternative terms is clean.
    A package licensed solely under GPL/AGPL/LGPL has exactly one alternative,
    that alternative is denied, and the package fails — so PyMuPDF (AGPL-3.0)
    still reddens this gate, which is the whole point.

    This is NOT a widening of the deny pattern. The pattern is unchanged and
    still exactly AGPL|GPL|LGPL. What this evaluates correctly is that a
    disjunctively licensed work may be taken under whichever of its own offered
    terms the recipient chooses, which is the same reasoning PLAN §12 R-11
    already applies to MPL. Every such choice is REPORTED LOUDLY on every run
    (see `check`) so it can never become a silent pass.
    """
    if expression.strip().upper() == UNKNOWN:
        return False, None, [UNKNOWN]
    terms = split_disjuncts(expression)
    denied = [t for t in terms if is_denied(t)]
    clean = [t for t in terms if not is_denied(t)]
    if clean:
        return True, clean[0], denied
    return False, None, denied


def universal_names() -> set[str]:
    """Package names in the UNIVERSAL lock closure (all platforms, all Pythons).

    A single-platform, single-Python resolution cannot see a marker-conditional
    dependency. This is the set the pinned measurement is checked against.
    """
    out = _run(
        ["uv", "tree", "--frozen", "--universal", "--no-dev"],
        stdout=subprocess.PIPE,
    ).stdout
    names: set[str] = set()
    for line in out.splitlines():
        # Strip tree drawing glyphs, then take the token before " v<version>".
        stripped = line.lstrip("│├└─ \t")
        match = re.match(r"^([A-Za-z0-9._-]+)(?:\[[^\]]*\])? v", stripped)
        if match:
            names.add(normalize(match.group(1)))
    return names


def cmd_generate(_: argparse.Namespace) -> int:
    python = ensure_pinned_env()

    # --no-license-path is load-bearing for determinism, not cosmetic: the path
    # embeds the absolute venv location, which differs between a laptop and a
    # CI runner and would make the freshness diff fail on a machine difference.
    # --ignore-packages pdf-tooling is LOAD-BEARING, not tidiness. pyproject's
    # [project] license-files lists THIRD_PARTY_LICENSES so the file ships inside
    # both artifacts (PLAN §11 / AC16). That makes pip-licenses --with-license-file
    # read this very file back out of pdf-tooling's own .dist-info and embed it in
    # the regenerated output — the inventory would contain a copy of itself and its
    # content would depend on how pdf-toolkit happened to be built and installed.
    # Excluding the first party from its own third-party inventory removes the
    # self-reference and is the semantically correct scope anyway.
    body = pip_licenses(
        python,
        "--format=plain-vertical",
        "--with-license-file",
        "--no-license-path",
        "--ignore-packages",
        SELF,
    )
    text = HEADER + "\n" + body.replace("\r\n", "\n").strip("\n") + "\n"
    INVENTORY.write_text(text, encoding="utf-8", newline="\n")
    print(f"[licenses] wrote {INVENTORY.name} ({len(text.splitlines())} lines)")

    # PDF-16's artifact. Written only when the website tree exists, so the
    # generator already works when PDF-16 lands and PDF-16 need not write one.
    if WEBSITE_DATA_DIR.is_dir():
        payload = rows(python, ignore_self=True)
        WEBSITE_JSON.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        print(f"[licenses] wrote {WEBSITE_JSON.relative_to(ROOT)} ({len(payload)} packages)")
    else:
        print("website/src/data/ absent — skipping licenses.json (PDF-16 creates it)")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    python = ensure_pinned_env(include_dev=args.informational)
    data = rows(python)

    offenders: list[dict[str, str]] = []
    disjunctive: list[tuple[dict[str, str], str, list[str]]] = []

    for row in data:
        name = str(row["Name"])
        permitted, relied_on, denied = evaluate_expression(str(row["License"]))
        if not permitted:
            if normalize(name) in {normalize(k) for k in ALLOWLIST}:
                print(f"[licenses] ALLOWLISTED: {name} — {ALLOWLIST[name]}")
                continue
            offenders.append(row)
        elif denied and relied_on is not None:
            disjunctive.append((row, relied_on, denied))

    measured = {normalize(str(r["Name"])) for r in data}
    print(f"[licenses] measured {len(measured)} packages in the pinned closure")

    # AC14 — the universal closure must be a subset of what we measured.
    # Skipped on the informational dev run, whose closure is a superset anyway.
    universal = set() if args.informational else universal_names()
    print(f"[licenses] universal lock closure lists {len(universal)} packages")
    unmeasured = sorted(universal - measured - {normalize(k) for k in MARKER_ONLY})
    if unmeasured:
        print("\nLICENSE GATE FAILED — universally-resolvable packages were never measured:")
        for name in unmeasured:
            print(f"  - {name}: not installable under the pinned resolution and not in MARKER_ONLY")
        print(
            "\nRemedy: verify the package's license from its own distribution metadata\n"
            "and record it in MARKER_ONLY in scripts/licenses.py with that license."
        )
        return 1
    for name, lic in sorted(MARKER_ONLY.items()):
        if normalize(name) in universal:
            print(f"[licenses] MARKER-ONLY: {name} — {lic} (not installable on the pinned leg)")

    if disjunctive:
        print(
            "\n[licenses] MULTI-LICENSE (disjunctive) — permitted under an alternative term.\n"
            "           Reported on every run so this can never become a silent pass."
        )
        for row, relied_on, denied in disjunctive:
            print(f"  - {row['Name']} {row['Version']}")
            print(f"      full expression : {row['License']}")
            print(f"      denied terms    : {'; '.join(denied)}")
            print(f"      RELIED UPON     : {relied_on}")

    if offenders:
        print("\nLICENSE GATE FAILED — denied or unknown licenses in the distributed closure:")
        for row in offenders:
            print(f"  - {row['Name']} {row['Version']}: {row['License']}")
        print(
            "\nDeny pattern is AGPL|GPL|LGPL (PLAN §7.2 mechanism 1). MPL is PERMITTED (R-11).\n"
            "An UNKNOWN license fails too: verify it from the distribution's own metadata and\n"
            "record it in ALLOWLIST with the reason the obligation does not reach this product.\n"
            "Do NOT widen the deny pattern."
        )
        return 0 if args.informational else 1

    print(f"\n[licenses] OK — {len(data)} packages, no AGPL/GPL/LGPL and no UNKNOWN.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="write THIRD_PARTY_LICENSES (+ website licenses.json)")
    gen.set_defaults(func=cmd_generate)

    chk = sub.add_parser("check", help="blocking license gate over the distributed closure")
    chk.add_argument(
        "--informational",
        action="store_true",
        help=(
            "measure the DEV tree and always exit 0 — the non-blocking "
            "informational run of PLAN §7.3"
        ),
    )
    chk.set_defaults(func=cmd_check)

    args = parser.parse_args(argv)
    result: int = args.func(args)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
